# fly.toml app configuration file generated for nhoi on 2025-10-24T15:44:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nhoi'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[autoscale]
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
